Joel/local storage
jteleha/group-project-1 pull request #16
Opened 2024-01-04 04:16 UTC by jteleha

2024-01-04 18:35 UTC, SpencerSurface requested changes
When I run the code, it breaks the existing event cards and carousel, and also doesn't show any recently viewed events. To be fair this may be due to something I did wrong when pulling the code, but based on what I saw we need to fix these problems before merging it into main.

2024-01-04 19:34 UTC, jteleha commented
> When I run the code, it breaks the existing event cards and carousel, and also doesn't show any recently viewed events. To be fair this may be due to something I did wrong when pulling the code, but based on what I saw we need to fix these problems before merging it into main.

Im going to take a look at it when I get home from work. I had some issues with my commits because the branch I was working on was not up to date so I think it's something I need to fix. Thanks for catching that.

2024-01-07 04:43 UTC, SpencerSurface approved these changes

2024-01-07 23:40 UTC, noah-10 approved these changes

2024-01-07 23:43 UTC, merged